# Generated by Django 3.2.13 on 2022-05-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='failed',
            field=models.IntegerField(default=1, help_text='失败总数', verbose_name='失败总数'),
            preserve_default=False,
        ),
    ]
