# Generated by Django 3.1 on 2022-06-19 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20220619_1517'),
        ('harbor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='harbor',
            name='repository',
            field=models.ForeignKey(default=123, help_text='所属项目', on_delete=django.db.models.deletion.CASCADE, to='repository.repository'),
        ),
    ]
