# Generated by Django 3.2.13 on 2022-05-31 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(help_text='id主键', primary_key=True, serialize=False, verbose_name='id主键')),
                ('name', models.CharField(help_text='工程名称', max_length=50, unique=True)),
                ('git', models.CharField(help_text='git仓库地址', max_length=200)),
                ('server', models.CharField(help_text='服务器地址', max_length=200)),
                ('type', models.CharField(help_text='工程类型', max_length=10)),
                ('address', models.CharField(help_text='企业微信地址', max_length=500)),
                ('send', models.BooleanField(help_text='是否发送')),
                ('build', models.TextField(help_text='构建前后步骤')),
            ],
        ),
    ]
