# Generated by Django 3.2.13 on 2022-06-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='build',
            field=models.TextField(blank=True, help_text='构建前后步骤', null=True),
        ),
    ]
