# Generated by Django 3.1 on 2022-06-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_alter_repository_build'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='address',
            field=models.CharField(blank=True, help_text='企业微信地址', max_length=500, null=True),
        ),
    ]
