# Generated by Django 3.2.13 on 2022-05-21 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0001_initial'),
        ('testcases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcases',
            name='interface',
            field=models.ForeignKey(help_text='所属接口', on_delete=django.db.models.deletion.CASCADE, to='interfaces.interfaces'),
        ),
    ]
