# Generated by Django 3.2.13 on 2022-06-08 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_alter_repository_build'),
        ('gitstatus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitstatus',
            name='respository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.repository'),
        ),
    ]
