# Generated by Django 3.1 on 2022-06-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitstatus', '0002_alter_gitstatus_respository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitstatus',
            name='structure_description',
            field=models.CharField(default='构建镜像', max_length=500),
        ),
    ]
